spring:
  application:
    name: no-more-oversell
  datasource:
    url: jdbc:mysql://localhost:3306/no_more_oversell?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: no_more_oversell
    password: no_more_oversell
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 5000
      max-lifetime: 270000
      maximum-pool-size: 30
  data:
    redis:
      timeout: ${REDIS_TIMEOUT:500ms}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/seed

checkout:
  cache:
    warm-up:
      enabled: true
      product-ids:
        - 900001
        - 900002

resilience4j:
  circuitbreaker:
    configs:
      redisCache:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      redisCache:
        baseConfig: redisCache
  timelimiter:
    configs:
      redisCache:
        timeoutDuration: 500ms
        cancelRunningFuture: true
    instances:
      redisCache:
        baseConfig: redisCache
